name: CI-CD Dev Pipeline

on:
  workflow_dispatch:
    inputs:
      ant_target:
        description: 'Please choose the ant target'
        required: true
        type: choice
        options:
          - clean
          - compile
          - build
          - test
          - run
run-name: Dev-CI-Pipeline:${{ inputs.ant_target }}

jobs:
  CI-Build:
    name: CI build Pipeline
    uses: dhakshna-learning/ci-cd-automation/.github/workflows/ci-build.yml@master
    with:
      ant_target: ${{ inputs.ant_target }}

      
