name: CI Pipeline - Reusable

on:
  push:
    branches: [ "rnd_feature" ]
  workflow_dispatch:

  jobs:
    runs-on: CICD

    steps: ANT Build
    uses: org/github-actions-reusable/.github/workflows/ci-build.yml@master
    with:
      ant_target: "compile test run"
