name: CI Pipeline - Reusable

on:
  push:
    branches: [ "rnd_feature" ]
  workflow_dispatch:

jobs:
  Trigerring-workflow:
    uses: dhakshna-learning/ci-cd-automation/.github/workflows/ci-build.yml@master
    with:
      ant_target: "compile test run"
